{% set name = "superqt" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af80d5687ec75df6c3e54119ee895e42f79742ed326684c79425414b5c20f1e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch
    - hatch-vcs
    - pip
    - python >=3.8
  run:
    - pyconify >=0.1.4
    - pygments >=2.4.0
    - python >=3.8
    - qtpy >=1.1.0
    - typing_extensions

test:
  imports:
    - superqt
  requires:
    - pip
    - pyqt
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/pyapp-kit/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other 
    extended widgets.
  dev_url: https://github.com/pyapp-kit/superqt

extra:
  recipe-maintainers:
    - goanpeca
    - jni
    - sofroniewn
    - tlambert03
