{% set name = "superqt" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87173fb04313176d68a51c5b8e920eee29f3d89959f6277979d574821ef755bf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch
    - hatch-vcs
    - pip
    - python >=3.7
  run:
    - packaging
    - pygments >=2.4.0
    - python >=3.7
    - qtpy >=1.1.0
    - typing-extensions

test:
  imports:
    - superqt
  requires:
    - pip
    - pyqt
  commands:
    - pip list
    - pip check

about:
  home: https://github.com/pyapp-kit/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other 
    extended widgets.
  dev_url: https://github.com/pyapp-kit/superqt

extra:
  recipe-maintainers:
    - goanpeca
    - jni
    - sofroniewn
    - tlambert03
